[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main,universe,restricted,multiverse


[Content]
Bootable=yes
Bootloader=grub
ShimBootloader=signed
BiosBootloader=none
Initrds=./builds/main
InitrdPackages=cryptsetup-initramfs
               libdevmapper1.02.1
               dmsetup
               kmod
               busybox-initramfs
               linux-modules-extra-azure

RootPassword=root
Packages=systemd
         kmod
         udev
         dbus
         tzdata
         tpm2-tools
         linux-azure
         linux-headers-azure
         grub-efi-amd64-signed
         grub-efi-amd64-bin
         shim-signed
         linux-firmware
         apparmor
         apparmor-utils
         iptables-persistent
         netfilter-persistent
         ca-certificates
         cloud-init
         openssl
         openssh-server
         walinuxagent

KernelCommandLine="console=ttyS0 earlyprintk=ttyS0 rootdelay=300 root=LABEL=root rw"

[Runtime]
Firmware=uefi-secure-boot
TPM=true

[Output]
Format = disk
ManifestFormat = json

[Build]
ToolsTree=default