[Distribution]
Distribution=ubuntu
Release=jammy
Architecture=x86-64
Repositories=main,universe,restricted,multiverse


[Content]
Bootable=yes
Bootloader=uki
InitrdPackages=cryptsetup-initramfs
               libdevmapper1.02.1
               dmsetup
               kmod
               busybox-initramfs

RootPassword=root
Packages=systemd
         kmod
         udev
         dbus
         tzdata
         tpm2-tools
         linux-azure
         linux-headers-azure
         grub-efi-amd64
         grub-efi-amd64-bin
         linux-firmware
         apparmor
         apparmor-utils
         iptables-persistent
         netfilter-persistent
         ca-certificates
         vim

KernelCommandLine="console=ttyS0 systemd.volatile=overlay"

[Runtime]
Firmware=uefi-secure-boot
TPM=true

[Output]
Format = disk
ManifestFormat = json

[Build]
ToolsTree=default