[Distribution]
Distribution=debian
Release=bookworm

[Output]
Format=gpt-verity
Bootable=yes
Initrd=yes
Kernel=yes

[Packages]
Packages=systemd openssh-server nano

[Verity]
Verity=yes

[Partition]
Size=2G