[Distribution]
Distribution=ubuntu

[Output]
Format=disk

[Content]
Bootable=true
Bootloader=grub
ShimBootloader=signed
BiosBootloader=none
RootPassword=ubuntu
Autologin=true
KernelCommandLine=console=ttyS0 earlyprintk=ttyS0 rootdelay=300
Hostname=ubuntu

Packages=
    apt
    dbus
    grub-efi-amd64-signed
    linux-virtual
    openssl
    shim-signed
    sudo
    systemd
    udev
    netplan.io
    openssh-server
    ssh-import-id
    vim

[Build]
ToolsTree=default



